create extension if not exists pgcrypto;

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  name_sq text not null,
  name_en text not null,
  category text not null default 'sneakers',
  image_key text not null default 'shooe_tilt_1.png',
  description_sq text not null default '',
  description_en text not null default '',
  price numeric(12,2) not null check (price >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null,
  role text not null default 'customer' check (role in ('customer','admin')),
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;
alter table public.profiles enable row level security;

create policy "products_public_read" on public.products for select using (active = true or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));
create policy "products_admin_insert" on public.products for insert with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));
create policy "products_admin_update" on public.products for update using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')) with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));
create policy "products_admin_delete" on public.products for delete using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));
create policy "profile_self_read" on public.profiles for select using (id = auth.uid());

insert into public.products (name_sq,name_en,category,image_key,description_sq,description_en,price)
select 'Nike Air Max 200','Nike Air Max 200','sneakers','shooe_tilt_1.png','Linja të pastra, stil i gjithanshëm dhe amortizim Max Air për rehati në çdo hap.','Clean lines, versatile style and Max Air cushioning for comfort in every step.',240
where not exists (select 1 from public.products where name_en='Nike Air Max 200');

insert into public.products (name_sq,name_en,category,image_key,description_sq,description_en,price)
select 'Nike Air Max 97','Nike Air Max 97','sneakers','shoe_tilt_2.png','Dizajn sportiv dhe komoditet i përditshëm me pamje ikonike.','Sporty design and everyday comfort with an iconic look.',220
where not exists (select 1 from public.products where name_en='Nike Air Max 97');

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  customer_name text not null,
  customer_email text not null,
  status text not null default 'new' check (status in ('new','confirmed','shipped','completed','cancelled')),
  total numeric(12,2) not null default 0,
  created_at timestamptz not null default now()
);
create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid not null references public.products(id),
  quantity integer not null check (quantity > 0 and quantity <= 99),
  unit_price numeric(12,2) not null
);
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
create policy "orders_admin_read" on public.orders for select using (exists (select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));
create policy "orders_admin_update" on public.orders for update using (exists (select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));
create policy "order_items_admin_read" on public.order_items for select using (exists (select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

create or replace function public.create_order(p_customer_name text, p_customer_email text, p_items jsonb)
returns uuid language plpgsql security definer set search_path = public as $$
declare
  v_order uuid;
  v_item jsonb;
  v_product uuid;
  v_qty integer;
  v_price numeric(12,2);
  v_total numeric(12,2) := 0;
begin
  if length(trim(p_customer_name)) < 2 or position('@' in p_customer_email) < 2 or jsonb_array_length(p_items) = 0 then
    raise exception 'Invalid order data';
  end if;
  insert into orders(customer_name,customer_email) values(trim(p_customer_name),lower(trim(p_customer_email))) returning id into v_order;
  for v_item in select * from jsonb_array_elements(p_items) loop
    v_product := (v_item->>'product_id')::uuid;
    v_qty := (v_item->>'quantity')::integer;
    if v_qty < 1 or v_qty > 99 then raise exception 'Invalid quantity'; end if;
    select price into v_price from products where id=v_product and active=true;
    if v_price is null then raise exception 'Product unavailable'; end if;
    insert into order_items(order_id,product_id,quantity,unit_price) values(v_order,v_product,v_qty,v_price);
    v_total := v_total + (v_price * v_qty);
  end loop;
  update orders set total=v_total where id=v_order;
  return v_order;
exception when others then
  if v_order is not null then delete from orders where id=v_order; end if;
  raise;
end; $$;
revoke all on function public.create_order(text,text,jsonb) from public;
grant execute on function public.create_order(text,text,jsonb) to anon, authenticated;
